### ISSUE TITLE
AndroidSupport lite/full requirement not specified

### ISSUE THREAD

**Issue by noamgat** [myflashlab/GoogleSignIn-ANE#3]
The documentation states that androidSupport.ane is required, which is reasonable.
However, it does not state, whether for the specific functions of this ANE, if the full or lite versions is required.
While we know you recommend the full, in our test devices we see that this is working with the lite, and using the full puts us over the multidex limit, which causes a bunch of other issues for us, so we are looking at using the lite one instead.
Do you know of any explicit usage of the google sign in library that would cause problems if we used the lite version of android support? Can this be specified in the docs of this great ANE?

**Comment by myflashlab** [comment]
The lite version is there mainly because of the barcode ANE. it helps that ANE to initialize faster. However, we always encourage users to use the full version.

If you are using the signin ANE only in your project and you are concerns about the little file size difference, you can safely use the lite version if you have tested and seen that everything works fine.

But if you are using other ANEs, and the little file size difference is not an issue, we recommend using the full version.

I hope this information is useful.
